defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .

model_name : attention
backbone: 'roberta-base'
data: '../data/eng_a_parsed.json'
num_labels: 7
lr: 1e-5
epochs: 8
batch_size: 16