model_name : deep
backbone: 'roberta-base'
data: '../data/merged_data.json'
model_path: '../outputs/models/task_a/large/deep'
stat_path: '../outputs/statistics/task_a/large/deep'
test: 'a'
weighted: False
mapping: full
num_labels: 7
lr: 1e-5
epochs: 8
batch_size: 32