model_name : attention
backbone: 'roberta-base'
data: '../data/eng_b_parsed.json'
model_path: '../outputs/models/task_b/attention'
stat_path: '../outputs/statistics/task_b/attention'
test: 'b'
weighted: True
num_labels: 16
lr: 1e-5
epochs: 8
batch_size: 16