model_name : max
backbone: 'roberta-base'
data: '../data/merged_data_c.json'
model_path: '../outputs/models/task_a/large/max'
stat_path: '../outputs/statistics/task_a/large/max'
test: 'a'
weighted: True
mapping: reduced
num_labels: 7
lr: 1e-5
epochs: 1
batch_size: 64