model_name : mean
backbone: 'roberta-base'
data: '../data/merged_data.json'
model_path: '../outputs/models/task_a/large/mean'
stat_path: '../outputs/statistics/task_a/large/mean'
test: 'a'
weighted: True
mapping: reduced
num_labels: 7
lr: 1e-5
epochs: 1
batch_size: 64