model_name : deep
backbone: 'roberta-base'
data: '../data/eng_a_parsed.json'
model_path: '../outputs/models/task_a/small/deep'
stat_path: '../outputs/statistics/task_a/small/deep'
test: 'a'
weighted: True
mapping: reduced
num_labels: 6
lr: 1e-5
epochs: 8
batch_size: 16