defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .

model: 'roberta-base'
data: '../data/codabench_data/train/combined'
num_labels: 7
lr: 1e-3
scheduler: 'cosine'
warmup_steps: 1000
epochs: 20
batch_size: 64